project:
  type: book
  output-dir: pdf # pdf

book:
  title: "Phân tích thống kê và vẽ đồ thị xuất sắc với R"
  author: "Duc Nguyen"
  date: last-modified
  date-format: "DD MMMM YYYY"
  cover-image: cover.png
  chapters:
    - index.qmd
    - vector.qmd
    - barchart.qmd
    - data_wrangling.qmd
    - format.qmd
    - references.qmd

bibliography: F:\\VAULT12\\LOCAL\\all.bib
csl: ieee.csl

format:
  html:
    theme: default
    toc: true
    toc-title: "Mục lục"
    toc-expand: 8
    toc-depth: 6
    toc-location: right
    number-sections: true
    number-depth: 8
    page-layout: full
    anchor-sections: true
    smooth-scroll: true
    # code-fold: true
    # grid:
    #   body-width: 1700px
    #   sidebar-width: 300px
    #   margin-width: 150px
  pdf:
    documentclass: scrreprt

knitr:
  opts_chunk: 
    message: false
    warning: false


